// <auto-generated />
using System;
using B1_TestTask_1.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace B1_TestTask_1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("B1_TestTask_1.Models.CalculationResult", b =>
                {
                    b.Property<double>("MedianOfDoubles")
                        .HasColumnType("float");

                    b.Property<decimal>("SumOfIntegers")
                        .HasColumnType("decimal(20,0)");

                    b.ToTable("CalculationResults");
                });

            modelBuilder.Entity("B1_TestTask_1.Models.StringsData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("DateColumn")
                        .HasColumnType("datetime2");

                    b.Property<double>("DoubleColumn")
                        .HasColumnType("float");

                    b.Property<int>("IntegerColumn")
                        .HasColumnType("int");

                    b.Property<string>("LatinCharsColumn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RussianCharsColumn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("StringsData");
                });
#pragma warning restore 612, 618
        }
    }
}
